var = input('Digite algo: ')
print('tipo: ', type(var))
print('Numero:', var.isnumeric())
print('Letras e numero:', var.isalnum())
print('Alfabético:', var.isalpha())
print('Maiusculo:', var.isupper())
